#!name= Enable Wi-Fi Call for Local VPN
#!desc= 允许在本地 VPN 上代理 Wi-Fi Call 流量
#!system=ios

[General]
include-all-networks = true
include-cellular-services = true

[Rule]
AND,((GEOIP,US),(AND,((PROTOCOL,UDP),(OR,((DEST-PORT,500),(DEST-PORT,4500)))))), 🇺🇲 美国节点
AND,((GEOIP,HK),(AND,((PROTOCOL,UDP),(OR,((DEST-PORT,500),(DEST-PORT,4500)))))), 🇭🇰 香港节点
AND,((GEOIP,GB),(AND,((PROTOCOL,UDP),(OR,((DEST-PORT,500),(DEST-PORT,4500)))))), 🇬🇧 英国节点